# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
---
publish-filters: &publish-filters
  filters:
    tags:
      only:
        - /^v.*/
    branches:
      ignore: /.*/

default-filters: &default-filters
  filters:
    tags:
      only:
        - /.*/

version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/computes/split-map-reduce-to-task
    steps:
      - checkout
      - run: >
          cat > ~/.netrc << EOF
            machine github.com
              login $GITHUB_USERNAME
              password $GITHUB_TOKEN
          EOF
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - persist_to_workspace:
          root: /go/src/github.com/computes
          paths:
            - split-map-reduce-to-task
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/computes/split-map-reduce-to-task
    steps:
      - attach_workspace:
          at: /go/src/github.com/computes
      - run: make crossrelease
      - persist_to_workspace:
          root: /go/src/github.com/computes
          paths:
            - split-map-reduce-to-task
  publish:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/computes/split-map-reduce-to-task
    steps:
      - attach_workspace:
          at: /go/src/github.com/computes
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u computes -replace "$CIRCLE_TAG" dist/release/

workflows:
  version: 2
  build-and-publish:
    jobs:
      - checkout_code:
          <<: *default-filters
      - build:
          <<: *default-filters
          requires:
            - checkout_code
      - publish:
          <<: *publish-filters
          requires:
            - build
